<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>파구스 운영</title></head><body>
<h1>파구스 운영자 화면</h1><p><?= esc(session('user_name')) ?>님</p>
<?php if (session('message')): ?><p role="status"><?= esc(session('message')) ?></p><?php endif; ?><?php if (session('error')): ?><p role="alert"><?= esc(session('error')) ?></p><?php endif; ?>
<form method="post" action="/logout"><?= csrf_field() ?><button type="submit">로그아웃</button></form>
<h2>카테고리</h2><form method="post" action="/admin/categories/save"><?= csrf_field() ?><input type="hidden" name="id" value="<?= $editingCategory === null ? '' : (int) $editingCategory['id'] ?>"><label>이름 <input name="name" required maxlength="100" value="<?= esc($editingCategory['name'] ?? old('name')) ?>"></label><button type="submit"><?= $editingCategory === null ? '등록' : '수정' ?></button><?php if ($editingCategory !== null): ?> <a href="/admin">취소</a><?php endif; ?></form>
<ul><?php foreach ($categories as $category): ?><li><?= esc($category['name']) ?> (<?= (int) $category['is_active'] === 1 ? '활성' : '숨김' ?>) <a href="/admin/categories/<?= (int) $category['id'] ?>/edit">수정</a> <form method="post" action="/admin/categories/<?= (int) $category['id'] ?>/toggle" style="display:inline"><?= csrf_field() ?><button type="submit"><?= (int) $category['is_active'] === 1 ? '숨김' : '활성화' ?></button></form></li><?php endforeach; ?></ul>
<h2><?= $editingRestaurant === null ? '맛집 등록' : '맛집 수정' ?></h2><form method="post" action="/admin/restaurants/save">
<?= csrf_field() ?><input type="hidden" name="id" value="<?= $editingRestaurant === null ? '' : (int) $editingRestaurant['id'] ?>">
<p><label>상호 <input name="name" required maxlength="150" value="<?= esc($editingRestaurant['name'] ?? old('name')) ?>"></label></p><p><label>주소 <input name="address" required maxlength="255" value="<?= esc($editingRestaurant['address'] ?? old('address')) ?>"></label></p>
<p><label>위도 <input name="latitude" required type="number" step="any" min="-90" max="90" value="<?= esc($editingRestaurant['latitude'] ?? old('latitude')) ?>"></label> <label>경도 <input name="longitude" required type="number" step="any" min="-180" max="180" value="<?= esc($editingRestaurant['longitude'] ?? old('longitude')) ?>"></label></p>
<p><label>연락처 <input name="phone" maxlength="30" value="<?= esc($editingRestaurant['phone'] ?? old('phone')) ?>"></label> <label>홈페이지 <input name="homepage_url" type="url" maxlength="2048" value="<?= esc($editingRestaurant['homepage_url'] ?? old('homepage_url')) ?>"></label></p>
<p>카테고리 <?php $selected = $editingRestaurant['category_ids'] ?? (array) old('category_ids');
foreach ($categories as $category): ?><label><input type="checkbox" name="category_ids[]" value="<?= (int) $category['id'] ?>" <?= in_array((int) $category['id'], array_map('intval', $selected), true) ? 'checked' : '' ?>><?= esc($category['name']) ?></label> <?php endforeach; ?></p>
<p><label>설명<br><textarea name="description"><?= esc($editingRestaurant['description'] ?? old('description')) ?></textarea></label></p><p><label>메뉴<br><textarea name="menu"><?= esc($editingRestaurant['menu'] ?? old('menu')) ?></textarea></label></p><p><label>영업 정보<br><textarea name="business_hours"><?= esc($editingRestaurant['business_hours'] ?? old('business_hours')) ?></textarea></label></p><p><label>태그 <input name="tags" maxlength="500" value="<?= esc($editingRestaurant['tags'] ?? old('tags')) ?>"></label></p>
<button type="submit">저장</button><?php if ($editingRestaurant !== null): ?> <a href="/admin">취소</a><?php endif; ?></form>
<h2>맛집 목록</h2><form method="get" action="/admin"><label>검색 <input name="q" value="<?= esc((string) ($this->request->getGet('q') ?? '')) ?>"></label><button type="submit">검색</button></form>
<table><thead><tr><th>상호</th><th>주소</th><th>카테고리</th><th>공개</th><th>관리</th></tr></thead><tbody><?php foreach ($restaurants as $restaurant): ?><tr><td><?= esc($restaurant['name']) ?></td><td><?= esc($restaurant['address']) ?></td><td><?= esc((string) ($restaurant['category_names'] ?? '')) ?></td><td><?= (int) $restaurant['is_published'] === 1 ? '공개' : '숨김' ?></td><td><a href="/admin/restaurants/<?= (int) $restaurant['id'] ?>/edit">수정</a> <form method="post" action="/admin/restaurants/<?= (int) $restaurant['id'] ?>/toggle" style="display:inline"><?= csrf_field() ?><button type="submit"><?= (int) $restaurant['is_published'] === 1 ? '숨김' : '공개' ?></button></form></td></tr><?php endforeach; ?></tbody></table>
</body></html>
