<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>파구스 운영</title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIINfQjCHJ1yMZ9QxY5G9L8B4mR4JvR8f6M=" crossorigin=""><style>#restaurant-map{height:320px;max-width:720px;margin:8px 0}.location-search{margin:8px 0}.location-search input{width:24rem;max-width:90%}#address-search-message{color:#555}.address-result{display:block;margin:4px 0;padding:6px;text-align:left}</style></head><body>
<h1>파구스 운영자 화면</h1><p><?= esc(session('user_name')) ?>님</p>
<?php if (session('message')): ?><p role="status"><?= esc(session('message')) ?></p><?php endif; ?><?php if (session('error')): ?><p role="alert"><?= esc(session('error')) ?></p><?php endif; ?>
<form method="post" action="/logout"><?= csrf_field() ?><button type="submit">로그아웃</button></form>
<h2>카테고리</h2><form method="post" action="/admin/categories/save"><?= csrf_field() ?><input type="hidden" name="id" value="<?= $editingCategory === null ? '' : (int) $editingCategory['id'] ?>"><label>이름 <input name="name" required maxlength="100" value="<?= esc($editingCategory['name'] ?? old('name')) ?>"></label><button type="submit"><?= $editingCategory === null ? '등록' : '수정' ?></button><?php if ($editingCategory !== null): ?> <a href="/admin">취소</a><?php endif; ?></form>
<ul><?php foreach ($categories as $category): ?><li><?= esc($category['name']) ?> (<?= (int) $category['is_active'] === 1 ? '활성' : '숨김' ?>) <a href="/admin/categories/<?= (int) $category['id'] ?>/edit">수정</a> <form method="post" action="/admin/categories/<?= (int) $category['id'] ?>/toggle" style="display:inline"><?= csrf_field() ?><button type="submit"><?= (int) $category['is_active'] === 1 ? '숨김' : '활성화' ?></button></form></li><?php endforeach; ?></ul>
<h2><?= $editingRestaurant === null ? '맛집 등록' : '맛집 수정' ?></h2><form method="post" action="/admin/restaurants/save">
<?= csrf_field() ?><input type="hidden" name="id" value="<?= $editingRestaurant === null ? '' : (int) $editingRestaurant['id'] ?>">
<p><label>상호 <input name="name" required maxlength="150" value="<?= esc($editingRestaurant['name'] ?? old('name')) ?>"></label></p><p><label>주소 <input id="restaurant-address" name="address" required maxlength="255" value="<?= esc($editingRestaurant['address'] ?? old('address')) ?>"></label></p>
<div class="location-search" id="address-search-form" role="search"><label for="address-search-query">주소 검색</label> <input id="address-search-query" minlength="2" maxlength="100" autocomplete="street-address"><button id="address-search-submit" type="button">검색</button><p id="address-search-message" role="status">검색 실패 시 주소와 좌표를 직접 입력할 수 있습니다.</p><div id="address-search-results"></div></div>
<div id="restaurant-map" aria-label="맛집 위치 선택 지도"></div>
<p><label>위도 <input id="restaurant-latitude" name="latitude" required type="number" step="any" min="-90" max="90" value="<?= esc($editingRestaurant['latitude'] ?? old('latitude')) ?>"></label> <label>경도 <input id="restaurant-longitude" name="longitude" required type="number" step="any" min="-180" max="180" value="<?= esc($editingRestaurant['longitude'] ?? old('longitude')) ?>"></label></p>
<p><label>연락처 <input name="phone" maxlength="30" value="<?= esc($editingRestaurant['phone'] ?? old('phone')) ?>"></label> <label>홈페이지 <input name="homepage_url" type="url" maxlength="2048" value="<?= esc($editingRestaurant['homepage_url'] ?? old('homepage_url')) ?>"></label></p>
<p>카테고리 <?php $selected = $editingRestaurant['category_ids'] ?? (array) old('category_ids');
foreach ($categories as $category): ?><label><input type="checkbox" name="category_ids[]" value="<?= (int) $category['id'] ?>" <?= in_array((int) $category['id'], array_map('intval', $selected), true) ? 'checked' : '' ?>><?= esc($category['name']) ?></label> <?php endforeach; ?></p>
<p><label>설명<br><textarea name="description"><?= esc($editingRestaurant['description'] ?? old('description')) ?></textarea></label></p><p><label>메뉴<br><textarea name="menu"><?= esc($editingRestaurant['menu'] ?? old('menu')) ?></textarea></label></p><p><label>영업 정보<br><textarea name="business_hours"><?= esc($editingRestaurant['business_hours'] ?? old('business_hours')) ?></textarea></label></p><p><label>태그 <input name="tags" maxlength="500" value="<?= esc($editingRestaurant['tags'] ?? old('tags')) ?>"></label></p>
<button type="submit">저장</button><?php if ($editingRestaurant !== null): ?> <a href="/admin">취소</a><?php endif; ?></form>
<h2>맛집 목록</h2><form method="get" action="/admin"><label>검색 <input name="q" value="<?= esc((string) (request()->getGet('q') ?? '')) ?>"></label><button type="submit">검색</button></form>
<table><thead><tr><th>상호</th><th>주소</th><th>카테고리</th><th>공개</th><th>관리</th></tr></thead><tbody><?php foreach ($restaurants as $restaurant): ?><tr><td><?= esc($restaurant['name']) ?></td><td><?= esc($restaurant['address']) ?></td><td><?= esc((string) ($restaurant['category_names'] ?? '')) ?></td><td><?= (int) $restaurant['is_published'] === 1 ? '공개' : '숨김' ?></td><td><a href="/admin/restaurants/<?= (int) $restaurant['id'] ?>/edit">수정</a> <form method="post" action="/admin/restaurants/<?= (int) $restaurant['id'] ?>/toggle" style="display:inline"><?= csrf_field() ?><button type="submit"><?= (int) $restaurant['is_published'] === 1 ? '숨김' : '공개' ?></button></form></td></tr><?php endforeach; ?></tbody></table>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script><script>
(() => {
    const address = document.getElementById('restaurant-address'); const latitude = document.getElementById('restaurant-latitude'); const longitude = document.getElementById('restaurant-longitude'); const message = document.getElementById('address-search-message'); const results = document.getElementById('address-search-results'); let marker = null;
    const validLocation = (lat, lon) => Number.isFinite(lat) && Number.isFinite(lon) && lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180;
    const map = window.L ? L.map('restaurant-map').setView([37.76, 126.78], 12) : null;
    if (map) { L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {attribution: '&copy; OpenStreetMap contributors', maxZoom: 19}).addTo(map); map.on('click', (event) => setLocation(event.latlng.lat, event.latlng.lng)); } else document.getElementById('restaurant-map').textContent = '지도를 불러오지 못했습니다. 아래 좌표를 직접 입력하세요.';
    function setLocation(lat, lon, label = '') { if (!validLocation(lat, lon)) return; latitude.value = lat.toFixed(7); longitude.value = lon.toFixed(7); if (label !== '') address.value = label; if (map) { if (marker) marker.setLatLng([lat, lon]); else marker = L.marker([lat, lon]).addTo(map); map.setView([lat, lon], Math.max(map.getZoom(), 15)); } }
    const initialLat = Number(latitude.value); const initialLon = Number(longitude.value); if (validLocation(initialLat, initialLon)) setLocation(initialLat, initialLon);
    const searchAddress = async () => { results.replaceChildren(); const query = document.getElementById('address-search-query').value.trim(); if (query.length < 2 || query.length > 100) { message.textContent = '주소 검색어는 2자 이상 100자 이하로 입력하세요.'; return; } const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 7000); message.textContent = '주소 검색 중...'; try { const response = await fetch('/admin/restaurants/search-address?q=' + encodeURIComponent(query), {signal: controller.signal, headers: {'Accept': 'application/json'}}); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || '주소 검색을 사용할 수 없습니다.'); if (!payload.results.length) { message.textContent = '검색 결과가 없습니다. 주소와 좌표를 직접 입력하세요.'; return; } message.textContent = '결과를 선택하면 주소와 좌표가 입력됩니다.'; payload.results.forEach((item) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'address-result'; button.textContent = item.display_name; button.addEventListener('click', () => setLocation(item.latitude, item.longitude, item.display_name)); results.append(button); }); } catch { message.textContent = '주소 검색을 사용할 수 없습니다. 주소와 좌표를 직접 입력하세요.'; } finally { clearTimeout(timer); } };
    document.getElementById('address-search-submit').addEventListener('click', searchAddress); document.getElementById('address-search-query').addEventListener('keydown', (event) => { if (event.key === 'Enter') { event.preventDefault(); searchAddress(); } });
})();
</script></body></html>
